### ISSUE TITLE
Maths plugin broken

### ISSUE THREAD

**Issue by xray7224** [xray7224/MegBot#72]
Gives the traceback

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Plugins/math.py", line 232, in main
    postfix(equation)
  File "Plugins/math.py", line 89, in postfix
    item = elem.calculate(stack[0], stack[1])
  File "Plugins/math.py", line 51, in calculate
    if operand2.value == 0:
AttributeError: 'float' object has no attribute 'value'
```

**Comment by moggers87** [comment]
Plugin was removed (it was in pretty bad shape and I'm sure @xray7224 could make something cleaner today)
