### ISSUE TITLE
help plugin doesn't list plugins

### ISSUE THREAD

**Issue by xray7224** [xray7224/MegBot#73]
When you try and list the plugins by doing !help this is probably due to the change to the loader we recently made.

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Plugins/help.py", line 26, in main
    amount = len(connection.plugins.keys())-1
AttributeError: 'Bot' object has no attribute 'plugins'
```

**Comment by moggers87** [comment]
Fixed in master at some point, help plugin works fine now.
